### ISSUE TITLE
Script doesn't work on ubuntu 20.04

### ISSUE THREAD

**Issue by sixcorners** [serverscope/serverscope-benchmark#31]
Some packages are no longer available
```
Package python-minimal is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  python2-minimal

E: Package 'python-minimal' has no installation candidate
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package libpython-stdlib is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libpython2-stdlib

E: Package 'libpython-stdlib' has no installation candidate
Can not install dependencies automatically.


```

**Comment by sixcorners** [comment]
Also fio doesn't build
```
Downloading & building fio from https://github.com/serverscope/serverscope-tools/raw/master/fio-2.8.tar.gz
FIO_VERSION = fio-2.8
In file included from crc/../os/os.h:33,
                 from crc/../thread_options.h:5,
                 from crc/../fio.h:18,
                 from crc/test.c:5:
crc/../os/os-linux.h:109:19: error: static declaration of ‘gettid’ follows non-static declaration
  109 | static inline int gettid(void)
      |                   ^~~~~~
In file included from /usr/include/unistd.h:1170,
                 from crc/../fio.h:12,
                 from crc/test.c:5:
/usr/include/x86_64-linux-gnu/bits/unistd_ext.h:34:16: note: previous declaration of ‘gettid’ was here
   34 | extern __pid_t gettid (void) __THROW;
      |                ^~~~~~
In file included from crc/../os/os.h:33,
                 from crc/../thread_options.h:5,
                 from crc/../fio.h:18,
                 from crc/test.c:5:
crc/../os/os-linux.h: In function ‘fio_lookup_raw’:
crc/../os/os-linux.h:171:6: warning: implicit declaration of function ‘major’ [-Wimplicit-function-declaration]
  171 |  if (major(dev) != RAW_MAJOR)
      |      ^~~~~
crc/../os/os-linux.h:184:17: warning: implicit declaration of function ‘minor’; did you mean ‘mincore’? [-Wimplicit-function-declaration]
  184 |  rq.raw_minor = minor(dev);
      |                 ^~~~~
      |                 mincore
make: *** [Makefile:300: crc/test.o] Error 1
Couldn't build fio. Exiting.

```

**Comment by MikeSchroll** [comment]
It probably should be upgraded to python3.

**Comment by valdo111** [comment]
Yes, same problem here

Full image URL: https://live.staticflickr.com/65535/50049659948_39eccfb4db_o.png

**Comment by Kramerican** [comment]
In addition, speedtest-cli needs to be installed with pip3 - otherwise an old and somehow broken version gets installed which doesn't accurately measure upload speed

**Comment by anton-ko** [comment]
This is fixed in https://github.com/serverscope/serverscope-benchmark/pull/34
